### ISSUE TITLE
[FEATURE] : ISSUE Template Bug Result

### ISSUE THREAD

**Issue by mogador26** [dnum-mi/referentiel-applications#367]
Définir un modèle de description de bug sous github. .github/ISSUE_TEMPLATE/BUG_REPORT.yml

exemple bug report de la console

```yaml

name: 🐛 Rapport de bug
description: Créer un ticket pour un bug.
title: "🐛 [BUG] - <title>"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Veuillez saisir une description explicite de votre problème.
      placeholder: Description courte et explicite de votre incident...
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: Etapes de reproduction
      description: Veuillez saisir une description explicite pour reproduire votre problème.
      value: |
        1. Aller à '...'
        2. Cliquer sur '....'
        3. Scroller jusqu'à '....'
        4. Voir l'erreur
      render: bash
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "Captures d'écran"
      description: Si nécessaire, ajoutez des captures d'écran pour expliquer votre problème.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Veuillez copier/coller tous les logs pertinents. Ces données seront automatiquement formatées en code.
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Navigateurs
      description: Quels sont les navigateurs sur lesquels vous constatez le problème ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Chromium
        - Brave
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Quels sont les systèmes d'exploitation sur lesquels vous constatez le problème ?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false

  - type: input
    id: affected-versions
    attributes:
      label: Version de la console impactée
      description: Quelle version de la console est impactée par le bug ?
      placeholder: v1.2.3
    validations:
      required: false

  - type: checkboxes
    id: dod
    attributes:
      label: Définition du fini
      description: Cochez les différents élément de la Definition Of Done.
      options:
        - label: Le correctif est terminé
          required: false
        - label: Les tests liés à ce correctif ont été ajoutés
          required: false
        - label: La communication avec les autres équipes impliquées par ce correctif a été faite
          required: false

```
